### ISSUE TITLE
Saved Replies: Line Break Issue / Edit from Dropdown

### ISSUE THREAD

**Issue by Marphies** [freescout-helpdesk/freescout#3448]
Thank you for this fantastic project! We use FreeScout's "Saved Replies" Module a lot!

I want to report one issue and one suggestion:

1. Since a recent update, all line breaks in saved replies are doubled (where there was one line break in a saved reply, there are now inserted two when adding the saved reply in the editor).
2. It would be fantastic when there was a way to edit a saved reply from the editor drop down if the user has permissions. At least a direct link to the Saved Replies Editor on the bottom of the editor dropdown would be great! Currently, it takes some effort to click through to the Saved Replies Editor when we want to change/correct a saved reply quickly while writing a reply.

Mockup:
![grafik](https://github.com/freescout-helpdesk/freescout/assets/147406642/d9505e88-6efc-41b8-bea0-061be5cb8b6a)

**Comment by freescout-helpdesk** [comment]
And specify your FreeScout and module's versions.

**Comment by Marphies** [comment]
That is a good hint. It seems that older Saved Replies have quite bad HTML code that leads to issues. Newer Saved Replies seem to work fine.

This one was working well with an older Freescout but now produces the doubled line breaks (Freescout 1.8.100, Saved Replies 1.0.31):
```html
<div>Dear Mr. {%customer.lastName%},</div>
<div>Thank you for your message.</div>
<div><br></div>
<div><br></div>
<div><br></div>
<div>If you have any further questions, we are always at your disposal.</div>
<div><br></div>
<div>Kind regards,</div>
<span style="font-size: 13.4px;">{%user.fullName%}</span>
```

Old result:
```
Dear Mr. {%customer.lastName%},
Thank you for your message.



If you have any further questions, we are always at your disposal.

Kind regards,
{%user.fullName%}
```

New result:
```
Dear Mr. {%customer.lastName%},

Thank you for your message.







If you have any further questions, we are always at your disposal.



Kind regards,
{%user.fullName%}
```

I know it is shitty HTML code, but it was produced by using the Freescout WYSIWYG editor.

**Comment by Marphies** [comment]
Following Saved Reply works well. It has an additional `<div>` tag. It also has a style attribute for every line.

```html
<div>
    <div style="font-size: 13.4px;">Dear Mrs. {%customer.lastName%},</div>
    <div style="font-size: 13.4px;">Thank you for your message.</div>
    <div style="font-size: 13.4px;"><br></div>
    <div style="font-size: 13.4px;"><br></div>
    <div style="font-size: 13.4px;"><br></div>
    <div style="font-size: 13.4px;">If you have any further questions, we are always at your disposal.</div>
    <div style="font-size: 13.4px;"><br></div>
    <div style="font-size: 13.4px;">Kind regards,</div>
</div>
<span style="font-size: 13.4px;">{%user.fullName%}</span>
```

Result:
```
Dear Mrs. {%customer.lastName%},
Thank you for your message.



If you have any further questions, we are always at your disposal.

Kind regards,
{%user.fullName%}
```

**Comment by Marphies** [comment]
Finally, this is what the current WYSIWYG editor is producing when just typing in the Saved Reply into a fresh editor:

```html
<div>
    <div>Dear Mr. {%customer.lastName%},</div>
    <div>Thank you for your message.</div>
    <div><br></div>
    <div><br></div>
    <div><br></div>
    <div>If you have any further questions, we are always at your disposal.</div>
    <div><br></div>
    <div>Kind regards,</div>
    <div>{%user.fullName%}</div>
</div>
```

Result:
```
Dear Mr. {%customer.lastName%},
Thank you for your message.



If you have any further questions, we are always at your disposal.

Kind regards,
{%user.fullName%}
```

**Comment by Marphies** [comment]
We now go in and fix all Saved Replies manually:

1. Copy reply as plain text
2. Switch editor to code view and delete everything
3. Switch back to HTML view and paste plain text
4. Save

It would be very helpful if HTML cleanup could be done by Freecout automatically for all Saved Replies automatically (maybe as a new plugin). Basically every reply produced by the WYSIWYG editor has messy HTML unless the user took extreme care and knows what he/she is doing.

**Comment by Marphies** [comment]
Just want to summarize this as the issue now basically contains three sub issues:

- [ ] Fix: Double line breaks on certain Saved Reply HTML code (see [here](https://github.com/freescout-helpdesk/freescout/issues/3448#issuecomment-1753105043))
- [ ] Feature: Adding Editor link to Saved Replies dropdown (see [here](https://github.com/freescout-helpdesk/freescout/issues/3448#issue-1933017771))
- [ ] Feature: Possibility to clean up Saved Replies HTML code for multiple items at once (see [here](https://github.com/freescout-helpdesk/freescout/issues/3448#issuecomment-1753130499))

Regarding the last point, the WYSIWYG editor has issues producing good HTML code. Are there any plans to integrate a different editor in general?

Alternatively, being able to switch the editor into a kind of a "minimal mode" would help a lot - this mode would only allow very basic HTML formatting such as bold, italic, quote, code, link, list and omit all other formatting while typing or copy/pasting. This way it should be quite easy to improve WYSIWYG HTML code quality dramatically.
Currently, especially font color, font size and 3rd party HTML code (like MS Word, Outlook while copy/pastic) is problematic even for experienced users. This leads to messed up Saved Replies and quite often odd looking ticket emails at the customers.

**Comment by freescout-helpdesk** [comment]
> Are there any plans to integrate a different editor in general?

Unfortunately not.
